### ISSUE TITLE
Is the Testing set not included in the official release?

### ISSUE THREAD

**Issue by JohnKilbride** [bao18/open_earth_map#2]
I downloaded the dataset from the [Zenodo link](https://zenodo.org/record/7223446). It seems like only the Training and Validation splits are included.

Is it possible the request the test set labels ? Thank you!

**Comment by bao18** [comment]
Thanks for your interest in the OpenEarthMap project. Yeah, labels for the testing set will not be available for now. But we will release a Codalab leaderboard within a week so that you can evaluate your implementations/predictions.

**Comment by JohnKilbride** [comment]
Awesome, thanks for the clarification! I have another question but will post that in a separate thread.
